### ISSUE TITLE
Extracting embeddings from model?

### ISSUE THREAD

**Issue by hmms117** [A4Bio/ProDesign#1]
Hi,

Thanks for sharing what looks like a very elegant method!

If one were to encode and extract representative embeddings of new structures (from pdb), how would this be done?

**Comment by gaozhangyang** [comment]
The colab may help you: https://colab.research.google.com/drive/1z6vpKA5L1iAmBLfREbmy8VNOtDYlkY4Q?usp=sharing

**Comment by hmms117** [comment]
Awesome, thanks! Perhaps a trivial question, but what feature(s) and layer(s) would you suggest to use as the embedding? I thought of using the hidden dimensions of V/E_distances, angles and directions.. - or would you use the last layer of the ProGNN?

X, S, score, _V, _E, E_idx, batch_id, mask_bw, mask_fw, decoding_order

**Comment by gaozhangyang** [comment]
I suggest to use the last layer of the ProGNN
