### ISSUE TITLE
TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by khushpatelmd** [A4Bio/ProDesign#5]
ON running this cell in the colab notebook, I am encoutering the error:
import torch
from ProDesign.main import Exp
from ProDesign.parser import create_parser
svpath = 'ProDesign/results/ProDesign/'
args = get_parser()
exp = Exp(args)

TypeError: exceptions must derive from BaseException

Colab notebook name is PredPDB

**Comment by buttercutter** [comment]
adding the following solved your issue

```python
!mkdir -p ProDesign/data/cath
!mkdir -p ProDesign/data/ts
!wget -O ProDesign/data/cath.zip https://github.com/A4Bio/PiFold/releases/download/Training%26Data/cath4.2.zip
!unzip ProDesign/data/cath.zip -d ProDesign/data/cath
!mv ProDesign/data/cath/cath4.2/* ProDesign/data/cath/

!wget -O ProDesign/data/ts.zip https://github.com/A4Bio/PiFold/releases/download/Training%26Data/ts.zip
!unzip ProDesign/data/ts.zip -d ProDesign/data/
```

**Comment by khushpatelmd** [comment]
Thank you
