### ISSUE TITLE
runtime error with batch_size=2

### ISSUE THREAD

**Issue by buttercutter** [A4Bio/ProDesign#6]
Could you help with the following runtime error with `batch_size`=2 ?

`python main.py --batch_size 2`

How to properly modify the value of `steps_per_epoch` variable in this case for non-default `batch_size` value ?  Why set `steps_per_epoch` to `1000` in the code ?

![Screenshot from 2023-04-11 15-00-59](https://user-images.githubusercontent.com/3324659/231097878-ccd0d291-7165-4586-8004-54456a1058d9.png)

![Screenshot from 2023-04-11 11-24-25](https://user-images.githubusercontent.com/3324659/231097932-bf162ea0-4c34-4d25-9fa2-c2d4ac592b00.png)

```python
Traceback (most recent call last):
  File "/home/phung/Downloads/PiFold/main.py", line 145, in <module>
    exp.train()
  File "/home/phung/Downloads/PiFold/main.py", line 73, in train
    train_loss, train_perplexity = self.method.train_one_epoch(
  File "/home/phung/Downloads/PiFold/methods/prodesign.py", line 49, in train_one_epoch
    self.scheduler.step()
  File "/home/phung/.local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 150, in step
    values = self.get_lr()
  File "/home/phung/.local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 1706, in get_lr
    raise ValueError("Tried to step {} times. The specified number of total steps is {}"
ValueError: Tried to step 100001 times. The specified number of total steps is 100000
```

**Comment by buttercutter** [comment]
if I move `scheduler.step()` away from within `train_one_epoch()` such that `scheduler.step()` should be invoked after each batch instead of after each epoch, then the loss convergence is so much slower.

Could you advise ?

![image](https://user-images.githubusercontent.com/3324659/232258482-f5fc931c-f617-4960-8eb6-7d2ef01fa039.png)

**Comment by gaozhangyang** [comment]
Sorry for the late response. You can refer to https://pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.OneCycleLR.html
