### ISSUE TITLE
the local coordinate system for the last residue seems to be zeros

### ISSUE THREAD

**Issue by imSeaton** [A4Bio/ProDesign#8]
```老哥你好，特别感谢你们的工作。`

simdesign_utils.py 
![image](https://user-images.githubusercontent.com/56856685/236460255-bf6fde18-75fb-4ca3-b7a3-dcdf6cb4e440.png)
文件中大概第148行的位置：
`Q = F.pad(Q, (0,0,0,1), 'constant', 0)` 
这里最后一个残基的局部坐标系全是0，请问为啥不用最后一个残基的骨干原子N, CA, C计算呢？看样子应该是可以计算的，是因为最后一个坐标系全设置为0比较简单并且对精度影响不大吗？

**Comment by gaozhangyang** [comment]
抱歉，回复迟了。你可以按照自己的需要改，这可能是bug或者我当时出于别的考量，我不是很记得了，但对模型性能影响不大。

**Comment by fourier20laplace** [comment]
u_0, u_1 = U[:,:-2,:], U[:,1:-1,:]#这里感觉得是U[:,:-1,:], U[:,1:,:]
这样才用到了最后一个氨基酸的坐标
